spring:
  profiles:
    active: local

project:
  root:
    path: /myprojects/kafka/

service:
  id: kafka

logging:
  file: ${project.root.path}/logs/${service.id}.log
  level:
    root: INFO
    ai: DEBUG


---
spring:
  profiles: local

camel:
  springboot:
    main-run-controller: true
    xmlRoutes: classpath:camel-routes/${service.id}/*.xml


kafka:
  server: localhost:9092
  topic: test
  input: ${project.root.path}/input/
  archive: ${project.root.path}/archive/

---


spring:
  profiles: dev

camel:
  springboot:
    main-run-controller: true
    xmlRoutes: classpath:camel-routes/${service.id}/kafka-route-csv-transaction.xml

kafka:
  server: localhost:9092
  topic: test
  input: ${project.root.path}/input/
  achive: ${project.root.path}/archive/
